language: ruby
rvm:
  - 2.1
install: gem install s3_website && bundle
script: JEKYLL_ENV=production jekyll build --baseurl https://bakkerlabs.nl
after_success: s3_website push

# safelist
branches:
  only:
  - master
  - stable